### ISSUE TITLE
Connector not starting with example-getting-started

### ISSUE THREAD

**Issue by fvolz** [industrial-data-space/trusted-connector#14]
**Describe the bug**
I try to run the example-getting-started with docker-compose. It throws a 501 error. I tried with different proxies, vpn but always same error.

**To Reproduce**
1. Download example
2. Start with docker-compose
3. See error

**Expected behavior**
Connector on localhost:8181

**Screenshots and logs**
ids-core_1    | org.apache.karaf.features.internal.util.MultiException: Error:
ids-core_1    |         Error downloading mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.spring-context-support/5.1.9.RELEASE_1
ids-core_1    |         at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:91)
ids-core_1    |         at org.apache.karaf.features.internal.download.impl.MavenDownloadManager.createDownloader(MavenDownloadManager.java:72)
ids-core_1    |         at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:457)
ids-core_1    |         at org.apache.karaf.features.internal.region.Subsystem.downloadBundles(Subsystem.java:452)
ids-core_1    |         at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:224)
ids-core_1    |         at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
ids-core_1    |         at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
ids-core_1    |         at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
ids-core_1    |         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
ids-core_1    |         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
ids-core_1    |         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
ids-core_1    |         at java.base/java.lang.Thread.run(Thread.java:834)
ids-core_1    |         Suppressed: java.io.IOException: Error downloading mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.spring-context-support/5.1.9.RELEASE_1
ids-core_1    |                 at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:77)
ids-core_1    |                 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
ids-core_1    |                 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
ids-core_1    |                 at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
ids-core_1    |                 ... 3 more
ids-core_1    |         Caused by: java.io.IOException: Error resolving artifact org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-context-support:jar:5.1.9.RELEASE_1: [Could not transfer artifact org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-context-support:jar:5.1.9.RELEASE_1 from/to central (http://repo1.maven.org/maven2/): Failed to transfer file http://repo1.maven.org/maven2/org/apache/servicemix/bundles/org.apache.servicemix.bundles.spring-context-support/5.1.9.RELEASE_1/org.apache.servicemix.bundles.spring-context-support-5.1.9.RELEASE_1.jar with status code 501]
ids-core_1    |                 at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.configureIOException(AetherBasedResolver.java:803)
ids-core_1    |                 at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:774)
ids-core_1    |                 at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:657)
ids-core_1    |                 at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:598)
ids-core_1    |                 at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:565)
ids-core_1    |                 at org.apache.karaf.features.internal.download.impl.MavenDownloadTask.download(MavenDownloadTask.java:52)
ids-core_1    |                 at org.apache.karaf.features.internal.download.impl.AbstractRetryableDownloadTask.run(AbstractRetryableDownloadTask.java:60)
ids-core_1    |                 ... 6 more
ids-core_1    |                 Suppressed: shaded.org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-context-support:jar:5.1.9.RELEASE_1 from/to central (http://repo1.maven.org/maven2/): Failed to transfer file http://repo1.maven.org/maven2/org/apache/servicemix/bundles/org.apache.servicemix.bundles.spring-context-support/5.1.9.RELEASE_1/org.apache.servicemix.bundles.spring-context-support-5.1.9.RELEASE_1.jar with status code 501
ids-core_1    |                         at shaded.org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
ids-core_1    |                         at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:368)
ids-core_1    |                         at shaded.org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
ids-core_1    |                         at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:642)
ids-core_1    |                         at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
ids-core_1    |                         at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:489)
ids-core_1    |                         at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:390)
ids-core_1    |                         at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
ids-core_1    |                         at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
ids-core_1    |                         at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
ids-core_1    |                         at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
ids-core_1    |                         ... 11 more
ids-core_1    |                 Caused by: shaded.org.apache.maven.wagon.TransferFailedException: Failed to transfer file http://repo1.maven.org/maven2/org/apache/servicemix/bundles/org.apache.servicemix.bundles.spring-context-support/5.1.9.RELEASE_1/org.apache.servicemix.bundles.spring-context-support-5.1.9.RELEASE_1.jar with status code 501
ids-core_1    |                         at shaded.org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1139)
ids-core_1    |                         at shaded.org.apache.maven.wagon.shared.http.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:1072)
ids-core_1    |                         at shaded.org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:126)
ids-core_1    |                         at shaded.org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
ids-core_1    |                         at shaded.org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
ids-core_1    |                         at shaded.org.eclipse.aether.transport.wagon.WagonTransporter$GetTaskRunner.run(WagonTransporter.java:567)
ids-core_1    |                         at shaded.org.eclipse.aether.transport.wagon.WagonTransporter.execute(WagonTransporter.java:435)
ids-core_1    |                         at shaded.org.eclipse.aether.transport.wagon.WagonTransporter.get(WagonTransporter.java:412)
ids-core_1    |                         at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:456)
ids-core_1    |                         at shaded.org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:363)
ids-core_1    |                         ... 20 more
ids-core_1    |         Caused by: shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Error resolving artifact org.apache.servicemix.bundles:org.apache.servicemix.bundles.spring-context-support:jar:5.1.9.RELEASE_1
ids-core_1    |                 at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:413)
ids-core_1    |                 at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:215)
ids-core_1    |                 at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:192)
ids-core_1    |                 at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:247)
ids-core_1    |                 at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:767)
ids-core_1    |                 ... 11 more

**Environment (please complete the following information):**
 - OS: Windows 64bit + Docker
 - Environment Docker Dekstop 2.3.0.3 (45519), Engine 19.03.08, Compose 1.25.5
 - Version 3.0.2

**Comment by gbrost** [comment]
Quick fix: You can configure your company proxy as described in this guide [guide](https://maven.apache.org/guides/mini/guide-proxies.html).

However, thank you for the finding. The connector should be self-contained without loading additional dependencies.

**Comment by gbrost** [comment]
I would like to keep this open to track down the dependency issue.

**Comment by gbrost** [comment]
Clarified. Was related to local build.
