### ISSUE TITLE
Connector not starting with example-getting-started

### ISSUE THREAD

**Issue by hylkevds** [industrial-data-space/trusted-connector#17]
### Steps to reproduce the behavior
Follow the 5 steps at https://industrial-data-space.github.io/trusted-connector-documentation/docs/getting_started/

docker-compose version 1.25.0
Docker version 18.09.1

### Expected behavior
As documented: The webconsole of the connector is available at http://localhost:8181/.

### Actual behavior

```
$ wget http://localhost:8181/
--2020-07-15 20:52:43--  http://localhost:8181/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8181... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.
```

Docker compose output:
```
example-getting-started $ docker-compose up
Starting example-getting-started_ids-ttpsim_1 ... done
Starting example-getting-started_ids-tpmsim_1 ... done
Starting example-getting-started_ids-core_1   ... done
Attaching to example-getting-started_ids-ttpsim_1, example-getting-started_ids-core_1, example-getting-started_ids-tpmsim_1
ids-tpmsim_1  | Starting swtpm (swtpm socket --tpmstate dir=/swtpm --tpm2 --server type=tcp,port=2321 --ctrl type=tcp,port=2322)...
ids-ttpsim_1  | [main] INFO org.eclipse.jetty.util.log - Logging initialized @432ms to org.eclipse.jetty.util.log.Slf4jLog
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.server.handler.ContextHandler - Empty contextPath
ids-ttpsim_1  | [main] INFO org.eclipse.jetty.server.Server - jetty-9.4.22.v20191022; built: 2019-10-22T13:37:13.455Z; git: b1e6b55512e008f7fbdf1cbea4ff8a6446d1073b; jvm 11.0.7+10
ids-ttpsim_1  | Jul 15, 2020 6:50:42 PM org.glassfish.jersey.internal.inject.Providers checkProviderRuntime
ids-ttpsim_1  | WARNING: A provider de.fhg.aisec.ids.attestation.REST registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider de.fhg.aisec.ids.attestation.REST will be ignored. 
ids-tpmsim_1  | Trying to execute "swtpm_ioctl -i --tcp localhost:2322"...
ids-tpmsim_1  | Trying to execute "swtpm_bios --tpm2 --tcp localhost:2321"...
ids-tpmsim_1  | Starting tpm2d...
ids-tpmsim_1  | 2020-07-15T18:50:42.286262+0000 [13] <INFO>  Starting tpm2d ...
ids-ttpsim_1  | [main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@2e5c7f0b{/,null,AVAILABLE}
ids-ttpsim_1  | [main] INFO org.eclipse.jetty.util.ssl.SslContextFactory - x509=X509@5bd73d1a(1,h=[localhost, repository.aisec.fraunhofer.de],w=[]) for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-tpmsim_1  | 2020-07-15T18:50:42.403717+0000 [13] <INFO>  out.pcrValues.digests[0].t.size 32
ids-tpmsim_1  | 2020-07-15T18:50:42.407151+0000 [13] <INFO>  pcrs[0]: size: 32
ids-tpmsim_1  |  PCR digest:  length 32
ids-tpmsim_1  |  66 68 7a ad f8 62 bd 77 6c 8f c1 8b 8e 9f 8e 20 
ids-tpmsim_1  |  08 97 14 85 6e e2 33 b3 90 2a 59 1d 0d 5f 29 25 
ids-tpmsim_1  |  policy digest:  length 32
ids-tpmsim_1  |  8b 56 82 d8 1b 29 43 5d 08 d7 92 78 15 06 11 dc 
ids-tpmsim_1  |  7e 59 23 b2 fe fc ce 68 4a 09 57 7b 40 13 0a 8b 
ids-tpmsim_1  | 2020-07-15T18:50:42.407355+0000 [13] <INFO>  Signing key for attestation found in /data/cml/tpm2d/tokens, nothing to be done.
ids-tpmsim_1  | 2020-07-15T18:50:42.407371+0000 [13] <INFO>  Sucessfully initialized TPM2.0
ids-tpmsim_1  | 2020-07-15T18:50:42.407468+0000 [13] <INFO>  created control socket.
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_RSA_WITH_AES_256_GCM_SHA384 enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_RSA_WITH_AES_128_GCM_SHA256 enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA256 enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_RSA_WITH_AES_256_CBC_SHA enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_ECDH_RSA_WITH_AES_256_CBC_SHA enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_DHE_RSA_WITH_AES_256_CBC_SHA enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_DHE_DSS_WITH_AES_256_CBC_SHA enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_RSA_WITH_AES_128_CBC_SHA256 enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_RSA_WITH_AES_128_CBC_SHA enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_RSA_WITH_AES_128_CBC_SHA enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_ECDH_RSA_WITH_AES_128_CBC_SHA enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_DHE_RSA_WITH_AES_128_CBC_SHA enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] WARN org.eclipse.jetty.util.ssl.SslContextFactory.config - Weak cipher suite TLS_DHE_DSS_WITH_AES_128_CBC_SHA enabled for Server@70d2e40b[provider=null,keyStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-keystore.jks,trustStore=jar:file:/root/rat-repository-3.0.2.jar!/repository-truststore.jks]
ids-ttpsim_1  | [main] INFO org.eclipse.jetty.server.AbstractConnector - Started ServerConnector@778d1062{SSL,[ssl, http/1.1]}{0.0.0.0:31337}
ids-ttpsim_1  | [main] INFO org.eclipse.jetty.server.Server - Started @1430ms

```

**Comment by gbrost** [comment]
Please uncomment the ports section in the docker-compose file of the side you wish to access.
8181 must be made available on either consumer or provider side.

**Comment by hylkevds** [comment]
There are no commented-out ports sections in the docker-compose file.

**Comment by gbrost** [comment]
So you use the files as contained in the zip file? So these ones are like the ones you use:
https://github.com/industrial-data-space/trusted-connector/tree/develop/examples/example-idscp
Then you have a section like this:
    # Enable this lines for debugging or UI access from localhost
#    ports:
#      - "5005:5005"
#      - "8181:8181"
#      - "8443:8443"
Right?

**Comment by hylkevds** [comment]
Nope, the file as I unzipped it has that section already non-commented.
And there is no comment "# Enable this lines for debugging or UI access from localhost"

**Comment by oxisto** [comment]
I just checked out the example, it seems that the current image uploaded to Dockerhub has an issue. By `exec`'into the running core container, and looking into the `log/karaf.log`, the following stacktrace shows up:

```
2020-07-16T13:48:14,442 | ERROR | CM Configuration Updater (Update: pid=org.ops4j.pax.url.mvn) | configadmin                      | 7 - org.apache.felix.configadmin - 1.9.16 | [org.osgi.service.cm.ManagedService, id=5, bundle=2/mvn:org.ops4j.pax.url/pax-url-aether/2.6.2]: Unexpected problem updating configuration org.ops4j.pax.url.mvn
shaded.org.apache.http.ssl.SSLInitializationException: problem accessing trust store
	at org.ops4j.pax.url.mvn.internal.HttpClients.createConnManager(HttpClients.java:85) ~[?:?]
	at org.ops4j.pax.url.mvn.internal.HttpClients.createClient(HttpClients.java:49) ~[?:?]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.<init>(AetherBasedResolver.java:168) ~[?:?]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.<init>(AetherBasedResolver.java:158) ~[?:?]
	at org.ops4j.pax.url.mvn.internal.Activator.updated(Activator.java:178) ~[?:?]
	at org.ops4j.pax.url.mvn.internal.Activator$OptionalConfigAdminHelper$1.updated(Activator.java:266) ~[?:?]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189) ~[!/:?]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152) [!/:?]
	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85) [!/:?]
	at org.apache.felix.cm.impl.ConfigurationManager$UpdateConfiguration.run(ConfigurationManager.java:1405) [!/:?]
	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:138) [!/:?]
	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:105) [!/:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.security.KeyStoreException: problem accessing trust store
	at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:73) ~[?:?]
	at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278) ~[?:?]
	at shaded.org.apache.http.ssl.SSLContextBuilder.loadTrustMaterial(SSLContextBuilder.java:224) ~[?:?]
	at org.ops4j.pax.url.mvn.internal.HttpClients.createConnManager(HttpClients.java:75) ~[?:?]
	... 12 more
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:792) ~[?:?]
	at sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:243) ~[?:?]
	at java.security.KeyStore.load(KeyStore.java:1479) ~[?:?]
	at sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:365) ~[?:?]
	at sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:313) ~[?:?]
	at sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:55) ~[?:?]
	at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49) ~[?:?]
	at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278) ~[?:?]
	at shaded.org.apache.http.ssl.SSLContextBuilder.loadTrustMaterial(SSLContextBuilder.java:224) ~[?:?]
	at org.ops4j.pax.url.mvn.internal.HttpClients.createConnManager(HttpClients.java:75) ~[?:?]
	... 12 more
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:790) ~[?:?]
	at sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:243) ~[?:?]
	at java.security.KeyStore.load(KeyStore.java:1479) ~[?:?]
	at sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:365) ~[?:?]
	at sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:313) ~[?:?]
	at sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:55) ~[?:?]
	at sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49) ~[?:?]
	at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278) ~[?:?]
	at shaded.org.apache.http.ssl.SSLContextBuilder.loadTrustMaterial(SSLContextBuilder.java:224) ~[?:?]
	at org.ops4j.pax.url.mvn.internal.HttpClients.createConnManager(HttpClients.java:75) ~[?:?]
	... 12 more
```

**Comment by oxisto** [comment]
Possibly related to https://github.com/industrial-data-space/trusted-connector/commit/167eb5bc43317014548ed78484893ff5a8c9bf73 ?

**Comment by gbrost** [comment]
> Nope, the file as I unzipped it has that section already non-commented.
> And there is no comment "# Enable this lines for debugging or UI access from localhost"
> 
> Do note that the tutorial points to "example-getting-started" not to "example-idscp"

Thanks for clarification. We will take a look.

**Comment by gbrost** [comment]
@hylkevds Could you please attach ../log/karaf.log? The output of docker compose is not sufficient. Thank you!
@oxisto You can just look at the local log file. Hm. The image i uploaded works with the changed examples. The zip file is not published yet. So the zip is out of sync. Please try the source example at https://github.com/industrial-data-space/trusted-connector/tree/develop/examples/example-getting-started
This works.

**Comment by hylkevds** [comment]
The output in ../log/karaf.log is the same as oxisto already posted.

**Comment by hylkevds** [comment]
Fixing the keystore and truststore entries in the system.properties makes things work.

**Comment by gbrost** [comment]
So this is indeed the same thing. I updated the zip file. Now everything should be fine (please give the stack few seconds after starting, if you try localhost:8181 immediately, you might get a browser error).

**Comment by gbrost** [comment]
Excellent. Sorry, you just hit the sweet spot between changing the source and updating the examples zip.
