### ISSUE TITLE
IDSCPv2 consumers cannot connect to remote broadcasting provider server

### ISSUE THREAD

**Issue by rizktouma** [industrial-data-space/trusted-connector#27]
**Describe the bug**
When trying to connect consumers to a broadcasting provider server on a remote machine using IDSCPv2, the connection cannot be established.

In the consumer logs, the following error is shown:

```
2020-12-14T14:27:17,322 | DEBUG | ForkJoinPool.commonPool-worker-15 | DefaultDapsDriver                | 57 - idscp2 - 1.0.0 | DAT is valid
2020-12-14T14:27:17,322 | DEBUG | ForkJoinPool.commonPool-worker-15 | StateClosed                      | 57 - idscp2 - 1.0.0 | Send IDSCP_HELLO
2020-12-14T14:27:17,372 | ERROR | ForkJoinPool.commonPool-worker-15 | TLSClient                        | 57 - idscp2 - 1.0.0 | Client cannot send data
2020-12-14T14:27:17,373 | ERROR | ForkJoinPool.commonPool-worker-15 | StateClosed                      | 57 - idscp2 - 1.0.0 | Cannot send IdscpHello. Close connection
2020-12-14T14:27:17,373 | DEBUG | ForkJoinPool.commonPool-worker-15 | StateClosed                      | 57 - idscp2 - 1.0.0 | Switched to state STATE_CLOSED
2020-12-14T14:27:17,374 | DEBUG | ForkJoinPool.commonPool-worker-15 | FSM                              | 57 - idscp2 - 1.0.0 | Shutting down FSM of connection 630b3ed7-299b-4f1b-88fc-aa850871b0b1...
```
Whereas the provider logs show this error:

```
2020-12-14T14:27:17,615 | DEBUG | HandshakeCompletedNotify-Thread | TLSServerThread                  | 56 - idscp2 - 1.0.0 | TLS Handshake was successful
2020-12-14T14:27:17,615 | DEBUG | HandshakeCompletedNotify-Thread | TLSSessionVerificationHelper     | 56 - idscp2 - 1.0.0 | Connected to 84.88.40.250:20454
2020-12-14T14:27:17,615 | DEBUG | HandshakeCompletedNotify-Thread | TLSSessionVerificationHelper     | 56 - idscp2 - 1.0.0 | Resolved IPs: 
2020-12-14T14:27:17,615 | WARN  | HandshakeCompletedNotify-Thread | TLSServerThread                  | 56 - idscp2 - 1.0.0 | TLS session is not valid. Close TLS connection
javax.net.ssl.SSLPeerUnverifiedException: Hostname verification failed. Peer certificate does not belong to peer host
	at de.fhg.aisec.ids.idscp2.drivers.default_driver_impl.secure_channel.TLSSessionVerificationHelper.verifyTlsSession(TLSSessionVerificationHelper.kt:102) ~[!/:?]
	at de.fhg.aisec.ids.idscp2.drivers.default_driver_impl.secure_channel.server.TLSServerThread.handshakeCompleted(TLSServerThread.kt:134) [!/:?]
	at sun.security.ssl.TransportContext$NotifyHandshake$1.run(TransportContext.java:663) [?:?]
	at sun.security.ssl.TransportContext$NotifyHandshake$1.run(TransportContext.java:660) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) [?:?]
	at sun.security.ssl.TransportContext$NotifyHandshake.run(TransportContext.java:660) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

This does not happen when both provider and consumer are on the same machine. I don't think it's an issue with the machines either, since using IDSCPv1 the consumer and provider on the same machines are able to connect without a problem.

**To Reproduce**
1. Clone the IDSCPv2 broadcasting example to two different machines from [here](https://github.com/industrial-data-space/trusted-connector/tree/develop/examples/example-idscp2)
2. Modify the consumer docker compose file to add "extra_hosts" to the consumer-core service as follows:

```
extra_hosts:
    - "provider-core:xx.xx.xx.xx"
```
where `xx.xx.xx.xx` is the public IP address of the machine where the provider will be running.
3. Modify the provider docker compose file to expose ports "29292:29292"
3. Execute the provider server with the modified docker compose file and wait for the initialization to finish.
4. Execute the consumer client with the modified docker compose file. When trying to establish an IDSCPv2 connection to the server, the errors mentioned above should appear in the logs.

**Expected behavior**
A connection should be established between the consumer and provider, and the messages broadcast by the provider should arrive to the consumers.

**Screenshots and logs**
[consumer-core-karaf.log](https://github.com/industrial-data-space/trusted-connector/files/5689533/consumer-core-karaf.log) (errors at lines 1414 and 1425)
[provider-core-karaf.log](https://github.com/industrial-data-space/trusted-connector/files/5689538/provider-core-karaf.log) (errors at lines 2647 and 2717)

**Environment (please complete the following information):**
 - OS: Windows 10 (consumer machine) and Linux Ubuntu (provider machine)
 - Environment: Docker containers
 - Version: pulled docker images right before execution this morning (not sure which commit they contain)

**Additional context**
N/A.

**Comment by milux** [comment]
Closing, because this issue is old and we have completely restructured the TC (switched from Karaf to Spring Boot) and especially IDSCP2.
If that issue is still relevant, please try with most recent TC 5 and open a new one.
